name: Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
      - uses: typst-community/setup-typst@v4
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          hugo --minify
          bash notes/compile.sh public/notes
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - uses: actions/deploy-pages@v4
